#!/bin/bash
# User custom scripts

historyawk() { history|awk '{a[$2]++}END{for(i in a){printf"%5d\t%s\n",a[i],i}}'|sort -nr|head; }

# Update requirements.txt based on setup.py
# run inside the same directory of setup.py
update_requirements_txt() {
   folder=$(basename $(pwd))
   package_name=${1-$folder}
   package_name=${package_name//_/-}
   virtualenv gen_req_venv
   source gen_req_venv/bin/activate
   pip install .
   pip freeze --local | grep -v "^$package_name==" > requirements.txt
   deactivate
   rm -rf gen_req_venv
}

# Create a dev virtualenv so I can run vim syntastic flak8 checks for that version of Python.
# Pyhton interpreter is first argument, defaults to system one
devenv() {
   if [ -d devenv ]
   then
     source devenv/bin/activate
   else
     if [ -z ${1+x} ]; then virtualenv devenv; else virtualenv devenv -p $1; fi
     source devenv/bin/activate
     pip install -r requirements.txt
     pip install -r requirements-dev.txt
   fi
}

# set GOPATH for projects using Gom
set_gopath() {
    export GOPATH=`pwd -L`:`pwd -L`/_vendor
}
