#!/bin/zsh
# Alias
alias ls='ls -G'
alias grep='grep --colour=auto'
# alias rm="rm -i"
# alias mv="mv -i"
alias la="ls -la"
alias p="pwd"
alias ll="ls -lah"

# DUH
alias duh="du --max-depth=1 -h --exclude=./.*"
alias duha="du --max-depth=1 -h"


# GIT specific settings
alias git-diff="git-diff --color"
alias git-list-branches="git for-each-ref --sort=-committerdate --format='%(color:yellow)%(refname:short)|%(color:bold green)%(committerdate:relative)|%(color:blue)%(subject)|%(color:magenta)%(authorname)%(color:reset)' | column -ts'|'"
alias git-list-remote-branches="git for-each-ref --sort=-committerdate refs/remotes --format='%(color:yellow)%(refname:short)|%(color:bold green)%(committerdate:relative)|%(color:blue)%(subject)|%(color:magenta)%(authorname)%(color:reset)' | column -ts'|'"
alias git-list-local-branches="git for-each-ref --sort=-committerdate refs/heads --format='%(color:yellow)%(refname:short)|%(color:bold green)%(committerdate:relative)|%(color:blue)%(subject)|%(color:magenta)%(authorname)%(color:reset)' | column -ts'|'"


# System stuff
alias shutdown="/sbin/shutdown -h now"
alias reboot="/sbin/reboot"


# Yelp
alias review-branch="python /Library/Python/2.7/site-packages/review_branch/main.py"
